# Amazing Mazes

Générateur et solveur de labyrinthe parfait inspiré par la mythologie grecque. Met en œuvre le Retour sur trace (Recursive Backtracking) et Kruskal pour la génération, le Retour sur trace et A* pour la résolution. Comprend la visualisation ASCII/image, l'analyse de performance et des tests sur des labyrinthes jusqu'à 100 000 cellules. Projet algorithmique Python avec benchmarks comparatifs.

In [3]:
# imports

# Outils dédiés à l'analyse des données via SQL
import duckdb
import pandas as pd

## Les constructeurs

### Recursive Backtracking

### Kruskal

#### Principe Général
L'algorithme de Kruskal génère des labyrinthes parfaits basés sur la théorie des MST (Minimum Spanning Tree), garantissant un unique chemin entre toute paire de cellules.

#### Fonctionnement
**Préparation** : Modélisation en graphe (cellules = nœuds), génération de toutes les arêtes adjacentes, randomisation.

**Construction** : Chaque cellule forme une composante connexe. Pour chaque arête randomisée, fusion des composantes si différentes (suppression du mur), sinon conservation pour éviter les cycles. Arrêt à n-1 arêtes ajoutées.

#### Caractéristiques Majeures
**Structure Union-Find** : Compression de chemin et union par rang pour l'optimisation.

**Propriétés** : Perfection (chemin unique), connectivité totale, absence de cycles, uniformité statistique.

#### Complexité Algorithmique
Pour un labyrinthe de taille n×n :
* **E = 2n(n-1)** arêtes au maximum
* **V = n²** cellules
* **Complexité finale** : O(n² log n)

### Kurskal strict

### Kurskal optimisé

#### Principe Général
Version optimisée de Kruskal éliminant le pré-stockage de toutes les arêtes. Génération et traitement à la volée des connexions adjacentes pour réduire drastiquement l'empreinte mémoire.

#### Fonctionnement
**Préparation** : Randomisation de l'ordre des cellules (non des arêtes). Aucun stockage préalable des connexions.
**Construction** : Pour chaque cellule dans l'ordre randomisé, génération dynamique des arêtes adjacentes (maximum 2), randomisation locale, puis application du critère Union-Find. Arrêt anticipé si labyrinthe complet.

#### Différences Majeures vs Kruskal Strict
**Génération dynamique** : Arêtes créées à la demande vs stockage exhaustif initial.
**Optimisation mémoire** : O(V) vs O(V + E) - élimination du stockage des ~2n² arêtes.
**Performance** : ~5x plus rapide sur grandes instances grâce à la réduction des allocations mémoire   et du tri global.

#### Complexité Algorithmique
Pour un labyrinthe n×n : **Complexité finale** : O(n²) vs O(n² log n)

## Les solveurs

### Recursive Backtracking

### A*

## Visalisations des labyrinthes et des parcours

## Analyse Comparative des Performances Algorithmiques

### Nos outils de mesures

Les métriques relevées permettent d’évaluer et de comparer les performances des algorithmes de génération de labyrinthes selon plusieurs dimensions.

Les informations d’identification assurent la traçabilité des expériences. Le champ `timestamp` enregistre la date et l’heure d’exécution, `filename` conserve le nom du fichier produit, `maze_size` indique la taille du labyrinthe, `seed` permet de reproduire la même génération, et `algorithm` identifie la méthode utilisée. Ces données garantissent la reproductibilité et facilitent le suivi de chaque test.

Les mesures de performance permettent de comparer l’efficacité temporelle et mémoire des algorithmes. La valeur `generation_time_ms` exprime la durée totale d’exécution en millisecondes, tandis que `ram_peak_mb` donne une estimation de la consommation mémoire maximale observée. Le champ `file_size_bytes` enregistre la taille finale du fichier ASCII produit, ce qui permet d’évaluer l’impact du stockage en fonction de la dimension du labyrinthe.

Des métriques spécifiques apportent un éclairage complémentaire selon l’algorithme étudié. Pour le backtracking récursif, `backtrack_count` mesure le nombre de retours en arrière effectués, traduisant la complexité de l’exploration. Pour Kruskal, `edges_processed` quantifie le nombre d’arêtes considérées, ce qui permet de comparer directement la version stricte et la version optimisée. Enfin, `union_find_operations` rend compte du nombre d’opérations internes de la structure Union-Find, indicateur de la charge algorithmique dans l’exécution de Kruskal.

L’ensemble de ces métriques permet de comparer les algorithmes sous trois angles complémentaires : la rapidité d’exécution, l’efficacité mémoire et la complexité pratique de leur mise en œuvre. Elles fournissent ainsi une base solide pour analyser les différences de performances entre le backtracking récursif, Kruskal strict et Kruskal optimisé.


### Les fichiers csv générés

**solver_metrics.csv** : Métriques d'évaluation des performances des algorithmes de résolution

**constructor_metrics.csv** : Métriques d'évaluation des performances des algorithmes de génération

### Liste des Labyrinthes Générés 

**Algorithme de Kruskal**
* 100 labyrinthes avec n=10, seeds de 1 à 100
* 100 labyrinthes avec n=20, seeds de 1 à 100
* 100 labyrinthes avec n=30, seeds de 1 à 100
* 99 labyrinthes avec n=40, seeds de 1 à 65 et 67 à 100
* 100 labyrinthes avec n=50, seeds de 1 à 100
* 50 labyrinthes avec n=100, seeds de 1 à 50
* 50 labyrinthes avec n=500, seeds de 1 à 50
* 50 labyrinthes avec n=1000, seeds de 1 à 50
* 20 labyrinthes avec n=5000, seeds de 1 à 20
* 5 labyrinthes avec n=6000, seeds de 66, 28, 150, 1 et 98

**Algorithme de Dfs**
* 100 labyrinthes avec n=10, seeds de 1 à 100
* 100 labyrinthes avec n=20, seeds de 1 à 100
* 100 labyrinthes avec n=30, seeds de 1 à 100
* 98 labyrinthes avec n=40, seeds de 1 à 65, 67 à 70 et 72 à 100 

In [78]:
df= pd.read_csv("constructors_metrics.csv")

df_counting = duckdb.sql(""" select
sum(case when maze_size = 10 and algorithm= 'kruskal' then 1 else 0 end) as Kruskal_10,
sum(case when maze_size = 10 and algorithm= 'recursive_backtracking' then 1 else 0 end) as Dfs_10,
sum(case when maze_size = 20 and algorithm= 'kruskal' then 1 else 0 end) as Kruskal_20,
sum(case when maze_size = 20 and algorithm= 'recursive_backtracking' then 1 else 0 end) as Dfs_20,
sum(case when maze_size = 30 and algorithm= 'kruskal' then 1 else 0 end) as Kruskal_30,
sum(case when maze_size = 30 and algorithm= 'recursive_backtracking' then 1 else 0 end) as Dfs_30,
sum(case when maze_size = 40 and algorithm= 'kruskal' then 1 else 0 end) as Kruskal_40,
sum(case when maze_size = 40 and algorithm= 'recursive_backtracking' then 1 else 0 end) as Dfs_40,
sum(case when maze_size = 50 and algorithm= 'kruskal' then 1 else 0 end) as Kruskal_50,
sum(case when maze_size = 100 and algorithm= 'kruskal' then 1 else 0 end) as Kruskal_100,
sum(case when maze_size = 500 and algorithm= 'kruskal' then 1 else 0 end) as Kruskal_500,
sum(case when maze_size = 1000 and algorithm= 'kruskal' then 1 else 0 end) as Kruskal_1000,
sum(case when maze_size = 5000 and algorithm= 'kruskal' then 1 else 0 end) as Kruskal_5000,
sum(case when maze_size = 6000 and algorithm= 'kruskal' then 1 else 0 end) as Kruskal_6000
from df """).df()

df_counting

Kruskal_10  Dfs_10  Kruskal_20  Dfs_20  Kruskal_30  Dfs_30  Kruskal_40  \
0       100.0   100.0       100.0   100.0       100.0   100.0        99.0   

   Dfs_40  Kruskal_50  Kruskal_100  Kruskal_500  Kruskal_1000  Kruskal_5000  \
0    98.0       100.0        100.0         50.0          50.0          20.0   

   Kruskal_6000  
0           5.0

## Recherche outliers

#### DFS

In [47]:
# création data frame dfs taille 10
df= pd.read_csv("constructors_metrics.csv")
df_recursive_maze_10 = duckdb.sql("""
SELECT * 
FROM df 
where maze_size = 10 and algorithm= 'recursive_backtracking'
""").df()

In [48]:
# Création data frame dfs taille 40
df= pd.read_csv("constructors_metrics.csv")
df_recursive_maze_40 = duckdb.sql("""
SELECT * 
FROM df 
where maze_size = 40 and algorithm= 'recursive_backtracking'
""").df()

#### Vérification des corrélations potentielles avec les autres métriques

In [97]:
# Vérification pour Dfs 10
# temps max
max_time = duckdb.sql("""
    SELECT *,
      'max_time'as metric
      from df_recursive_maze_10
        where generation_time_ms = (select max(generation_time_ms) FROM df_recursive_maze_10)""").df()



# max operations
max_ops = duckdb.sql("""
    SELECT *,
      'max_ops'as metric
    from df_recursive_maze_10
    where backtrack_count = (select max(backtrack_count) FROM df_recursive_maze_10)""").df()

result = duckdb.sql(""" 
    select * from max_time
    union all
    select * from max_ops
    """).df()

result

timestamp              filename  maze_size  seed  \
0  2025-09-17 19:13:21  recursive_maze_10_50       10.0  50.0   
1  2025-09-17 19:13:21  recursive_maze_10_43       10.0  43.0   

                algorithm  generation_time_ms  ram_peak_mb  file_size_bytes  \
0  recursive_backtracking                9.92        17.68            483.0   
1  recursive_backtracking                1.63        17.68            483.0   

   backtrack_count  edges_processed  union_find_operations    metric  
0             12.0             99.0                    0.0  max_time  
1             14.0             99.0                    0.0   max_ops

In [50]:
# Vérifiaction pour Dfs 40
# temps max
max_time = duckdb.sql("""
    SELECT *,
      'max_time'as metric
      from df_recursive_maze_40
        where generation_time_ms = (select max(generation_time_ms) FROM df_recursive_maze_40)""").df()



# max operations
max_ops = duckdb.sql("""
    SELECT *,
      'max_ops'as metric
    from df_recursive_maze_40
    where backtrack_count = (select max(backtrack_count) FROM df_recursive_maze_40)""").df()

result = duckdb.sql(""" 
    select * from max_time
    union all
    select * from max_ops
    """).df()

result

timestamp              filename  maze_size  seed  \
0  2025-09-17 19:21:28  recursive_maze_40_65       40.0  65.0   
1  2025-09-17 19:26:54  recursive_maze_40_79       40.0  79.0   

                algorithm  generation_time_ms  ram_peak_mb  file_size_bytes  \
0  recursive_backtracking                31.9        18.27           6723.0   
1  recursive_backtracking                12.3        18.26           6723.0   

   backtrack_count  edges_processed  union_find_operations    metric  
0            157.0           1599.0                    0.0  max_time  
1            177.0           1599.0                    0.0   max_ops

### Kruskal

In [84]:
# Création dataframe Kruskal 10
df= pd.read_csv("constructors_metrics.csv")
df_kruskal_10= duckdb.sql("""
SELECT * 
FROM df 
where maze_size = 10 and algorithm= 'kruskal'
""").df()

In [99]:
# Création dataframe Kruskal 20
df= pd.read_csv("constructors_metrics.csv")
df_kruskal_20= duckdb.sql("""
SELECT * 
FROM df 
where maze_size = 20 and algorithm= 'kruskal'
""").df()

In [85]:
# Création dataframe Kruskal 50
df= pd.read_csv("constructors_metrics.csv")
df_kruskal_50 = duckdb.sql("""
SELECT * 
FROM df 
where maze_size = 50 and algorithm= 'kruskal'
""").df()

In [86]:
# Création dataframe Kruskal 1000
df= pd.read_csv("constructors_metrics.csv")
df_kruskal_1000 = duckdb.sql("""
SELECT * 
FROM df 
where maze_size = 1000 and algorithm= 'kruskal'
""").df()

### Vérification des corrélations potentielles avec les autres métriques

In [105]:
# Vérification sur Kruskal 10
# temps max
max_time = duckdb.sql("""
    SELECT *,
      'max_time'as metric
      from df_kruskal_10
        where generation_time_ms = (select max(generation_time_ms) FROM df_kruskal_10)""").df()

# max operations
max_ops = duckdb.sql("""
    SELECT *,
      'max_ops'as metric
    from df_kruskal_50
    where union_find_operations = (select max(union_find_operations) FROM df_kruskal_10)""").df()

result = duckdb.sql(""" 
    select * from max_time
    union all
    select * from max_ops
    """).df()

result

timestamp                 filename  maze_size  seed algorithm  \
0  2025-09-16 19:01:40  kruskal_strict_10_3.txt       10.0   3.0   kruskal   

   generation_time_ms  ram_peak_mb  file_size_bytes  backtrack_count  \
0               15.33        17.99            483.0              0.0   

   edges_processed  union_find_operations    metric  
0            180.0                  639.0  max_time

In [106]:
# Vérification sur Kruskal 20
# temps max
max_time = duckdb.sql("""
    SELECT *,
      'max_time'as metric
      from df_kruskal_20
        where generation_time_ms = (select max(generation_time_ms) FROM df_kruskal_20)""").df()

# max operations
max_ops = duckdb.sql("""
    SELECT *,
      'max_ops'as metric
    from df_kruskal_20
    where union_find_operations = (select max(union_find_operations) FROM df_kruskal_20)""").df()

result = duckdb.sql(""" 
    select * from max_time
    union all
    select * from max_ops
    """).df()

result

timestamp                  filename  maze_size  seed algorithm  \
0  2025-09-20 13:18:10   kruskal_strict_20_5.txt       20.0   5.0   kruskal   
1  2025-09-20 13:18:10  kruskal_strict_20_24.txt       20.0  24.0   kruskal   

   generation_time_ms  ram_peak_mb  file_size_bytes  backtrack_count  \
0               15.53        17.94           1763.0              0.0   
1                2.43        17.95           1763.0              0.0   

   edges_processed  union_find_operations    metric  
0            760.0                 2858.0  max_time  
1            760.0                 3212.0   max_ops

In [104]:
# Vérification sur Kruskal 50
# temps max
max_time = duckdb.sql("""
    SELECT *,
      'max_time'as metric
      from df_kruskal_50
        where generation_time_ms = (select max(generation_time_ms) FROM df_kruskal_50)""").df()

# max operations
max_ops = duckdb.sql("""
    SELECT *,
      'max_ops'as metric
    from df_kruskal_50
    where union_find_operations = (select max(union_find_operations) FROM df_kruskal_50)""").df()

result = duckdb.sql(""" 
    select * from max_time
    union all
    select * from max_ops
    """).df()

result

timestamp                  filename  maze_size  seed algorithm  \
0  2025-09-16 19:01:40  kruskal_strict_50_17.txt       50.0  17.0   kruskal   
1  2025-09-16 19:01:41  kruskal_strict_50_86.txt       50.0  86.0   kruskal   

   generation_time_ms  ram_peak_mb  file_size_bytes  backtrack_count  \
0               47.26        18.96          10403.0              0.0   
1               10.41        18.97          10403.0              0.0   

   edges_processed  union_find_operations    metric  
0           4900.0                20906.0  max_time  
1           4900.0                21611.0   max_ops

In [90]:
# Vérification sur Kruskal 1000
# temps max
max_time = duckdb.sql("""
    SELECT *,
      'max_time'as metric
      from df_kruskal_1000
        where generation_time_ms = (select max(generation_time_ms) FROM df_kruskal_1000)""").df()

# max ram
max_ram = duckdb.sql("""
    SELECT *,
      'max_ram'as metric
    from df_kruskal_1000
    where ram_peak_mb = (select max(ram_peak_mb) FROM df_kruskal_1000)""").df()

# max operations
max_ops = duckdb.sql("""
    SELECT *,
      'max_ops'as metric
    from df_kruskal_1000
    where union_find_operations = (select max(union_find_operations) FROM df_kruskal_1000)""").df()

result = duckdb.sql(""" 
    select * from max_time
    union all
    select * from max_ram
    union all
    select * from max_ops
    """).df()

result

timestamp                    filename  maze_size  seed algorithm  \
0  2025-09-16 19:14:33  kruskal_strict_1000_39.txt     1000.0  39.0   kruskal   
1  2025-09-16 19:11:22  kruskal_strict_1000_16.txt     1000.0  16.0   kruskal   
2  2025-09-16 19:11:05  kruskal_strict_1000_14.txt     1000.0  14.0   kruskal   

   generation_time_ms  ram_peak_mb  file_size_bytes  backtrack_count  \
0           198485.63       294.39        4008003.0              0.0   
1             8018.94       298.02        4008003.0              0.0   
2             8073.97       296.01        4008003.0              0.0   

   edges_processed  union_find_operations    metric  
0        1998000.0              8807356.0  max_time  
1        1998000.0              8720812.0   max_ram  
2        1998000.0              8922923.0   max_ops

#### Traitement: les outliers generation_time_ms sont fixés à la moyenne de generation_time_ms 

In [112]:
df_clean = duckdb.sql("""
SELECT 
    filename,
    algorithm,
    union_find_operations, 
    timestamp,
    maze_size,
    CASE 
        WHEN filename = 'kruskal_strict_20_5.txt' THEN 
            (SELECT mean(generation_time_ms) FROM df WHERE maze_size = 20 AND algorithm = 'kruskal')
        WHEN filename = 'kruskal_strict_10_3.txt' THEN 
            (SELECT mean(generation_time_ms) FROM df WHERE maze_size = 10 AND algorithm = 'kruskal')
        WHEN filename = 'kruskal_strict_1000_39.txt' THEN 
            (SELECT mean(generation_time_ms) FROM df WHERE maze_size = 1000 AND algorithm = 'kruskal')
        WHEN filename = 'recursive_maze_10_50' THEN 
            (SELECT mean(generation_time_ms) FROM df WHERE maze_size = 10 AND algorithm = 'recursive_backtracking')
        WHEN filename = 'recursive_maze_40_65' THEN 
            (SELECT mean(generation_time_ms) FROM df WHERE maze_size = 40 AND algorithm = 'recursive_backtracking')
        ELSE generation_time_ms
    END as generation_time_ms
FROM df
""").df()

filename               algorithm  union_find_operations  \
0  kruskal_strict_1000_39.txt                 kruskal              8807356.0   
1     kruskal_strict_10_3.txt                 kruskal                  639.0   
2     kruskal_strict_20_5.txt                 kruskal                 2858.0   
3        recursive_maze_10_50  recursive_backtracking                    0.0   
4        recursive_maze_40_65  recursive_backtracking                    0.0   

             timestamp  maze_size  generation_time_ms  
0  2025-09-16 19:14:33     1000.0        12405.770600  
1  2025-09-16 19:01:40       10.0            1.561600  
2  2025-09-20 13:18:10       20.0            2.434900  
3  2025-09-17 19:13:21       10.0            1.601600  
4  2025-09-17 19:21:28       40.0           10.018878

### Analyse des outliers

#### Observations
Les pics de RAM les plus importants sont toujours sur les derniers enregistrements d'une série pour Kruskal et Recursive Backtracking.

#### Outliers détectés
**Kruskal** (3 outliers) : Kruskal_10 (15.33 ms), Kruskal_50 (47.26 ms), Kruskal_1000 (198,485.63 ms)

**Recursive Backtracking** (2 outliers) : Recursive_maze_40 (31.9 ms), Recursive_maze_10 (9.92 ms)

#### Traitement
Nous n'avons constaté aucune corrélation entre ces temps d'exécution excessifs et les autres métriques. L'origine des outliers n'étant pas expliquée, remplacement par la moyenne de generation_time_ms.

# Brouillon = > Ne pas prendre en compte

In [44]:
# selection des colonnes numériques
num_col = ['generation_time_ms', 'ram_peak_mb', 'file_size_bytes', 'edges_processed', 'union_find_operations']

for column in num_col:
    Q1 = df_kruskal_10[column].quantile(0.25)
    Q3 = df_kruskal_10[column].quantile(0.75)
    IQR = Q3 - Q1 

    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 - 1.5*IQR

    outliers = df_kruskal_10[(df_kruskal_10[column] > upper_bound) |
               (df_kruskal_10[column]  < lower_bound)]

    print(f"\n{column}:")
    print(f"  - Q1: {Q1:.2f}, Q3: {Q3:.2f}, IQR: {IQR:.2f}")
    print(f"  - Bornes: [{lower_bound:.2f}, {upper_bound:.2f}]")
    print(f"  - Outliers détectés: {len(outliers)}")
    
    if len(outliers) > 0:
        print(f"  - Valeurs outliers: {outliers[column].values}")


generation_time_ms:
  - Q1: 1.07, Q3: 1.65, IQR: 0.58
  - Bornes: [0.20, 0.78]
  - Outliers détectés: 100
  - Valeurs outliers: [ 2.02  2.01 15.33  2.19  2.3   1.77  1.35  2.67  1.59  1.92  2.2   1.3
  0.86  0.98  1.43  2.59  1.47  1.37  1.1   1.03  1.14  1.25  0.99  2.5
  1.32  1.48  2.34  1.25  0.88  1.56  2.17  1.42  1.18  0.98  1.38  1.2
  1.14  2.98  1.09  0.91  1.55  0.84  0.84  1.27  1.11  1.26  1.19  1.29
  2.22  0.97  1.32  0.84  0.96  1.14  1.78  1.06  1.2   1.43  1.16  0.86
  1.1   1.29  0.78  0.8   2.03  1.48  1.48  2.01  0.91  1.09  1.32  0.86
  2.59  1.4   2.23  1.6   1.35  0.87  0.82  0.82  1.7   0.94  1.26  1.63
  1.36  1.47  1.26  1.03  2.37  1.07  1.88  1.32  1.11  0.89  1.12  1.32
  0.95  2.54  1.21  1.97]

ram_peak_mb:
  - Q1: 18.00, Q3: 18.01, IQR: 0.01
  - Bornes: [17.98, 17.99]
  - Outliers détectés: 85
  - Valeurs outliers: [17.97 18.   18.   18.   18.   18.   18.   18.   18.   18.   18.   18.
 18.   18.   18.   18.   18.   18.   18.   18.   18.   18.   18.   1

In [69]:
# selection des colonnes numériques
num_col = ['generation_time_ms', 'ram_peak_mb', 'file_size_bytes', 'edges_processed', 'union_find_operations']

for column in num_col:
    Q1 = df_kruskal_1000[column].quantile(0.25)
    Q3 = df_kruskal_1000[column].quantile(0.75)
    IQR = Q3 - Q1 

    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 - 1.5*IQR

    outliers = df_kruskal_1000[(df_kruskal_1000[column] > upper_bound) |
               (df_kruskal_1000[column]  < lower_bound)]

    print(f"\n{column}:")
    print(f"  - Q1: {Q1:.2f}, Q3: {Q3:.2f}, IQR: {IQR:.2f}")
    print(f"  - Bornes: [{lower_bound:.2f}, {upper_bound:.2f}]")
    print(f"  - Outliers détectés: {len(outliers)}")
    
    if len(outliers) > 0:
        print(f"  - Valeurs outliers: {outliers[column].values}")


generation_time_ms:
  - Q1: 7974.09, Q3: 8469.40, IQR: 495.31
  - Bornes: [7231.13, 7726.44]
  - Outliers détectés: 50
  - Valeurs outliers: [  7947.67   7917.07   7980.88   7990.86   7971.83   7736.82   7856.33
   7954.05   8003.37   8023.8    8042.64   7767.68   7943.84   8073.97
   8028.93   8018.94   8005.09   7863.18   7947.29   8030.15   8250.04
   8177.29   8132.14   7776.34   8112.15   8224.4    8041.29   9767.64
  10055.48   8479.43  10170.42   8130.95   8084.38   8024.92   8054.17
   8017.76   7900.42   8355.62 198485.63   8439.32   8321.86   7821.53
   8668.36  10703.69  11055.26  10778.68  11374.85  10879.34  11327.57
  11573.21]

ram_peak_mb:
  - Q1: 293.71, Q3: 295.73, IQR: 2.01
  - Bornes: [290.69, 292.71]
  - Outliers détectés: 45
  - Valeurs outliers: [294.33 293.66 295.68 295.71 296.63 294.52 295.57 295.55 293.66 295.95
 293.67 294.78 296.01 296.22 298.02 289.68 293.7  295.73 296.73 296.85
 293.64 293.75 296.84 294.36 295.33 294.51 296.45 295.34 294.37 295.46
 294.39

## Recherche de corrélations des variables sur les outliers

In [82]:


# temps max
max_time = duckdb.sql("""
    SELECT *,
      'max_time'as metric
      from df_kruskal_1000
        where generation_time_ms = (select max(generation_time_ms) FROM df_kruskal_1000)""").df()

# max ram
max_ram = duckdb.sql("""
    SELECT *,
      'max_ram'as metric
    from df_kruskal_1000
    where ram_peak_mb = (select max(ram_peak_mb) FROM df_kruskal_1000)""").df()

# max operations
max_ops = duckdb.sql("""
    SELECT *,
      'max_ops'as metric
    from df_kruskal_1000
    where union_find_operations = (select max(union_find_operations) FROM df_kruskal_1000)""").df()

result = duckdb.sql(""" 
    select * from max_time
    union all
    select * from max_ram
    union all
    select * from max_ops
    """).df()

result

timestamp                    filename  maze_size  seed algorithm  \
0  2025-09-16 19:14:33  kruskal_strict_1000_39.txt     1000.0  39.0   kruskal   
1  2025-09-16 19:11:22  kruskal_strict_1000_16.txt     1000.0  16.0   kruskal   
2  2025-09-16 19:11:05  kruskal_strict_1000_14.txt     1000.0  14.0   kruskal   

   generation_time_ms  ram_peak_mb  file_size_bytes  backtrack_count  \
0           198485.63       294.39        4008003.0              0.0   
1             8018.94       298.02        4008003.0              0.0   
2             8073.97       296.01        4008003.0              0.0   

   edges_processed  union_find_operations    metric  
0        1998000.0              8807356.0  max_time  
1        1998000.0              8720812.0   max_ram  
2        1998000.0              8922923.0   max_ops

In [73]:
result = duckdb.sql("""
SELECT *
from df_kruskal_50
where union_find_operations = (
select max(union_find_operations)
from df_kruskal_50)
""").df()
result

timestamp                  filename  maze_size  seed algorithm  \
0  2025-09-16 19:01:41  kruskal_strict_50_86.txt       50.0  86.0   kruskal   

   generation_time_ms  ram_peak_mb  file_size_bytes  backtrack_count  \
0               10.41        18.97          10403.0              0.0   

   edges_processed  union_find_operations  
0           4900.0                21611.0

In [74]:
result = duckdb.sql("""
SELECT *
from df_kruskal_10
where union_find_operations = (
select max(union_find_operations)
from df_kruskal_10)
""").df()
result

timestamp                  filename  maze_size  seed algorithm  \
0  2025-09-16 19:01:40  kruskal_strict_10_43.txt       10.0  43.0   kruskal   

   generation_time_ms  ram_peak_mb  file_size_bytes  backtrack_count  \
0                0.84         18.0            483.0              0.0   

   edges_processed  union_find_operations  
0            180.0                  774.0

### recherche correlation avec la ram

In [77]:
result = duckdb.sql("""
SELECT *
from df_kruskal_50
where ram_peak_mb = (
select max(ram_peak_mb)
from df_kruskal_50)
""").df()
result

timestamp                   filename  maze_size   seed  \
0   2025-09-16 19:01:41   kruskal_strict_50_79.txt       50.0   79.0   
1   2025-09-16 19:01:41   kruskal_strict_50_80.txt       50.0   80.0   
2   2025-09-16 19:01:41   kruskal_strict_50_81.txt       50.0   81.0   
3   2025-09-16 19:01:41   kruskal_strict_50_82.txt       50.0   82.0   
4   2025-09-16 19:01:41   kruskal_strict_50_83.txt       50.0   83.0   
5   2025-09-16 19:01:41   kruskal_strict_50_84.txt       50.0   84.0   
6   2025-09-16 19:01:41   kruskal_strict_50_85.txt       50.0   85.0   
7   2025-09-16 19:01:41   kruskal_strict_50_86.txt       50.0   86.0   
8   2025-09-16 19:01:41   kruskal_strict_50_87.txt       50.0   87.0   
9   2025-09-16 19:01:41   kruskal_strict_50_88.txt       50.0   88.0   
10  2025-09-16 19:01:41   kruskal_strict_50_89.txt       50.0   89.0   
11  2025-09-16 19:01:41   kruskal_strict_50_90.txt       50.0   90.0   
12  2025-09-16 19:01:41   kruskal_strict_50_91.txt       50.0   91.0   
13  2025-09-16 19:01:41   kruskal_strict_50_92.txt       50.0   92.0   
14  2025-09-16 19:01:41   kruskal_strict_50_93.txt       50.0   93.0   
15  2025-09-16 19:01:41   kruskal_strict_50_94.txt       50.0   94.0   
16  2025-09-16 19:01:41   kruskal_strict_50_95.txt       50.0   95.0   
17  2025-09-16 19:01:41   kruskal_strict_50_96.txt       50.0   96.0   
18  2025-09-16 19:01:41   kruskal_strict_50_97.txt       50.0   97.0   
19  2025-09-16 19:01:41   kruskal_strict_50_98.txt       50.0   98.0   
20  2025-09-16 19:01:41   kruskal_strict_50_99.txt       50.0   99.0   
21  2025-09-16 19:01:41  kruskal_strict_50_100.txt       50.0  100.0   

   algorithm  generation_time_ms  ram_peak_mb  file_size_bytes  \
0    kruskal               10.32        18.97          10403.0   
1    kruskal               10.00        18.97          10403.0   
2    kruskal                9.90        18.97          10403.0   
3    kruskal               14.18        18.97          10403.0   
4    kruskal               14.94        18.97          10403.0   
5    kruskal               10.75        18.97          10403.0   
6    kruskal                9.10        18.97          10403.0   
7    kruskal               10.41        18.97          10403.0   
8    kruskal               10.74        18.97          10403.0   
9    kruskal                9.11        18.97          10403.0   
10   kruskal                9.67        18.97          10403.0   
11   kruskal               11.01        18.97          10403.0   
12   kruskal                9.39        18.97          10403.0   
13   kruskal               11.59        18.97          10403.0   
14   kruskal                8.95        18.97          10403.0   
15   kruskal               10.41        18.97          10403.0   
16   kruskal               10.04        18.97          10403.0   
17   kruskal               10.06        18.97          10403.0   
18   kruskal               10.21        18.97          10403.0   
19   kruskal               10.90        18.97          10403.0   
20   kruskal                9.98        18.97          10403.0   
21   kruskal                9.88        18.97          10403.0   

    backtrack_count  edges_processed  union_find_operations  
0               0.0           4900.0                19169.0  
1               0.0           4900.0                18806.0  
2               0.0           4900.0                19348.0  
3               0.0           4900.0                20242.0  
4               0.0           4900.0                19417.0  
5               0.0           4900.0                19977.0  
6               0.0           4900.0                20158.0  
7               0.0           4900.0                21611.0  
8               0.0           4900.0                18804.0  
9               0.0           4900.0                20050.0  
10              0.0           4900.0                18870.0  
11              0.0           4900.0                19536.0  
12              0.0           49

In [4]:
df= pd.read_csv("constructors_metrics.csv")
df_recursive_maze_10 = duckdb.sql("""
SELECT * 
FROM df 
where maze_size = 10 and algorithm= 'recursive_backtracking'
""").df()
df_recursive_maze_10

timestamp               filename  maze_size   seed  \
0   2025-09-17 19:13:21    recursive_maze_10_1       10.0    1.0   
1   2025-09-17 19:13:21    recursive_maze_10_2       10.0    2.0   
2   2025-09-17 19:13:21    recursive_maze_10_3       10.0    3.0   
3   2025-09-17 19:13:21    recursive_maze_10_4       10.0    4.0   
4   2025-09-17 19:13:21    recursive_maze_10_5       10.0    5.0   
..                  ...                    ...        ...    ...   
95  2025-09-17 19:13:21   recursive_maze_10_96       10.0   96.0   
96  2025-09-17 19:13:21   recursive_maze_10_97       10.0   97.0   
97  2025-09-17 19:13:21   recursive_maze_10_98       10.0   98.0   
98  2025-09-17 19:13:21   recursive_maze_10_99       10.0   99.0   
99  2025-09-17 19:13:21  recursive_maze_10_100       10.0  100.0   

                 algorithm  generation_time_ms  ram_peak_mb  file_size_bytes  \
0   recursive_backtracking                1.16        17.62            483.0   
1   recursive_backtracking                1.04        17.65            483.0   
2   recursive_backtracking                1.74        17.65            483.0   
3   recursive_backtracking                1.73        17.65            483.0   
4   recursive_backtracking                1.46        17.65            483.0   
..                     ...                 ...          ...              ...   
95  recursive_backtracking                1.15        17.68            483.0   
96  recursive_backtracking                0.94        17.68            483.0   
97  recursive_backtracking                1.14        17.68            483.0   
98  recursive_backtracking                1.18        17.68            483.0   
99  recursive_backtracking                1.07        17.68            483.0   

    backtrack_count  edges_processed  union_find_operations  
0               8.0             99.0                    0.0  
1               9.0             99.0                    0.0  
2               8.0             99.0                    0.0  
3              10.0             99.0                    0.0  
4               9.0             99.0                    0.0  
..              ...              ...                    ...  
95              8.0             99.0                    0.0  
96              7.0             99.0                    0.0  
97             11.0             99.0                    0.0  
98             13.0             99.0                    0.0  
99              9.0             99.0                    0.0  

[100 rows x 11 columns]

In [6]:
# selection des colonnes numériques
num_col = ['generation_time_ms', 'ram_peak_mb', 'file_size_bytes', 'edges_processed', 'union_find_operations']

for column in num_col:
    Q1 = df_recursive_maze_10[column].quantile(0.25)
    Q3 = df_recursive_maze_10[column].quantile(0.75)
    IQR = Q3 - Q1 

    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 - 1.5*IQR

    outliers = df_recursive_maze_10[(df_recursive_maze_10[column] > upper_bound) |
               (df_recursive_maze_10[column]  < lower_bound)]

    print(f"\n{column}:")
    print(f"  - Q1: {Q1:.2f}, Q3: {Q3:.2f}, IQR: {IQR:.2f}")
    print(f"  - Bornes: [{lower_bound:.2f}, {upper_bound:.2f}]")
    print(f"  - Outliers détectés: {len(outliers)}")
    
    if len(outliers) > 0:
        print(f"  - Valeurs outliers: {outliers[column].values}")


generation_time_ms:
  - Q1: 1.10, Q3: 1.73, IQR: 0.63
  - Bornes: [0.15, 0.78]
  - Outliers détectés: 100
  - Valeurs outliers: [1.16 1.04 1.74 1.73 1.46 3.51 1.57 1.33 1.6  1.25 1.53 1.63 1.17 2.56
 1.65 1.25 1.27 1.38 1.64 1.76 1.56 2.69 1.84 1.63 1.98 1.92 1.43 1.98
 1.43 1.2  1.93 1.1  1.77 1.32 1.13 1.78 1.6  1.53 1.43 2.   1.18 1.09
 1.63 1.14 1.19 3.08 1.26 1.05 1.28 9.92 2.45 2.75 1.39 4.27 1.62 4.43
 1.39 1.9  1.03 0.97 2.26 1.14 1.46 0.96 1.73 1.   1.01 1.12 2.01 1.32
 0.96 0.91 1.62 1.36 1.02 1.02 0.94 0.97 1.24 0.91 1.15 1.06 1.07 2.2
 1.05 1.09 0.96 1.1  1.01 1.11 2.63 1.2  1.6  0.98 1.01 1.15 0.94 1.14
 1.18 1.07]

ram_peak_mb:
  - Q1: 17.67, Q3: 17.68, IQR: 0.01
  - Bornes: [17.66, 17.67]
  - Outliers détectés: 85
  - Valeurs outliers: [17.62 17.65 17.65 17.65 17.65 17.65 17.65 17.65 17.67 17.67 17.67 17.67
 17.67 17.67 17.67 17.67 17.67 17.67 17.67 17.67 17.67 17.67 17.67 17.67
 17.67 17.67 17.67 17.68 17.68 17.68 17.68 17.68 17.68 17.68 17.68 17.68
 17.68 17.68 17.68 

In [9]:
# selection des colonnes numériques
num_col = ['generation_time_ms', 'ram_peak_mb', 'file_size_bytes', 'edges_processed', 'union_find_operations']

for column in num_col:
    Q1 = df_recursive_maze_40[column].quantile(0.25)
    Q3 = df_recursive_maze_40[column].quantile(0.75)
    IQR = Q3 - Q1 

    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 - 1.5*IQR

    outliers = df_recursive_maze_40[(df_recursive_maze_40[column] > upper_bound) |
               (df_recursive_maze_40[column]  < lower_bound)]

    print(f"\n{column}:")
    print(f"  - Q1: {Q1:.2f}, Q3: {Q3:.2f}, IQR: {IQR:.2f}")
    print(f"  - Bornes: [{lower_bound:.2f}, {upper_bound:.2f}]")
    print(f"  - Outliers détectés: {len(outliers)}")
    
    if len(outliers) > 0:
        print(f"  - Valeurs outliers: {outliers[column].values}")


generation_time_ms:
  - Q1: 7.80, Q3: 11.13, IQR: 3.33
  - Bornes: [2.81, 6.14]
  - Outliers détectés: 98
  - Valeurs outliers: [ 7.16  8.9  10.89  6.98  7.75  8.49  6.9   9.51 13.73 12.57 11.72 10.
 11.4   7.78 10.51 10.99 10.74 10.97 14.42  9.25  7.4  10.4   9.93  7.8
  7.38  8.09  7.8   8.85 10.27 12.45 10.19  7.81  7.21  9.3  10.41  7.6
 10.66  9.48  9.33  6.97  8.18  9.25  7.19  8.04  9.34  7.65  7.63  8.27
  6.93  7.81  7.25  9.12 10.67  7.    8.54  9.82  7.59  7.6  11.31 11.24
 10.98 11.22  7.49  8.36 31.9  10.94 13.39 10.78  7.83  8.93 11.18  9.4
  7.19 21.02  7.04 12.3  16.4  10.81 13.41 11.52 11.61 12.3   8.1   9.92
 10.95 12.14 11.85 14.64  8.43  7.07  8.99  8.18  7.38 11.79 12.58  8.43
  8.11 16.87]

ram_peak_mb:
  - Q1: 18.21, Q3: 18.27, IQR: 0.06
  - Bornes: [18.12, 18.18]
  - Outliers détectés: 82
  - Valeurs outliers: [18.09 18.2  18.2  18.2  18.2  18.2  18.21 18.21 18.21 18.21 18.21 18.21
 18.21 18.21 18.21 18.21 18.21 18.21 18.21 18.21 18.21 18.21 18.21 18.21
 18.22 

In [ ]:
max(generation_time_ms) as max_time_ms, min(generation_time_ms) as min_time_ms, avg(generation_time_ms) as avg_time_ms 

In [ ]:
kurskal et recursive_backtracking: les pic de ram les plus importants sont toujours sur les derniers enregistrements d'une serie
kurskal: 3 outliers détectés Kurskal_10 =>15.33, kurskal_50 =>47.26 kuskal_1000 => 198485.63 
recursive_backtracking: 2 outliers détectés recursive_maze_40 =>31.9 et recursive_maze_10 =>9.92
kurskal: après étude approfondie aucune répercution de ces valeurs extrême sur ram_peak_mb, union_find_operations. Dans ces conditions nous décidons de remplacer ces valeurs par la moyenne de generation_time_ms

In [57]:
# création data frame dfs taille 20
df= pd.read_csv("constructors_metrics.csv")
df_recursive_maze_20 = duckdb.sql("""
SELECT * 
FROM df 
where maze_size = 20 and algorithm= 'recursive_backtracking'
""").df()
df_recursive_maze_20

timestamp               filename  maze_size   seed  \
0   2025-09-20 13:14:42    recursive_maze_20_1       20.0    1.0   
1   2025-09-20 13:14:42    recursive_maze_20_2       20.0    2.0   
2   2025-09-20 13:14:42    recursive_maze_20_3       20.0    3.0   
3   2025-09-20 13:14:42    recursive_maze_20_4       20.0    4.0   
4   2025-09-20 13:14:42    recursive_maze_20_5       20.0    5.0   
..                  ...                    ...        ...    ...   
95  2025-09-20 13:14:42   recursive_maze_20_96       20.0   96.0   
96  2025-09-20 13:14:42   recursive_maze_20_97       20.0   97.0   
97  2025-09-20 13:14:42   recursive_maze_20_98       20.0   98.0   
98  2025-09-20 13:14:42   recursive_maze_20_99       20.0   99.0   
99  2025-09-20 13:14:42  recursive_maze_20_100       20.0  100.0   

                 algorithm  generation_time_ms  ram_peak_mb  file_size_bytes  \
0   recursive_backtracking                2.50        17.71           1763.0   
1   recursive_backtracking                2.38        17.76           1763.0   
2   recursive_backtracking                2.32        17.76           1763.0   
3   recursive_backtracking                3.91        17.76           1763.0   
4   recursive_backtracking                3.60        17.76           1763.0   
..                     ...                 ...          ...              ...   
95  recursive_backtracking                2.51        17.82           1763.0   
96  recursive_backtracking                2.39        17.82           1763.0   
97  recursive_backtracking                4.40        17.82           1763.0   
98  recursive_backtracking                3.10        17.82           1763.0   
99  recursive_backtracking                2.72        17.82           1763.0   

    backtrack_count  edges_processed  union_find_operations  
0              42.0            399.0                    0.0  
1              37.0            399.0                    0.0  
2              44.0            399.0                    0.0  
3              39.0            399.0                    0.0  
4              41.0            399.0                    0.0  
..              ...              ...                    ...  
95             38.0            399.0                    0.0  
96             37.0            399.0                    0.0  
97             45.0            399.0                    0.0  
98             38.0            399.0                    0.0  
99             41.0            399.0                    0.0  

[100 rows x 11 columns]

In [59]:
max_recursive_20 = duckdb.sql("""
SELECT max("generation_time_ms")
from df_recursive_maze_20
""").df()
max_recursive_20

max(generation_time_ms)
0                     5.75

In [60]:
# création data frame dfs taille 30
df= pd.read_csv("constructors_metrics.csv")
df_recursive_maze_30 = duckdb.sql("""
SELECT * 
FROM df 
where maze_size = 30 and algorithm= 'recursive_backtracking'
""").df()
df_recursive_maze_30

timestamp               filename  maze_size   seed  \
0   2025-09-20 13:14:42    recursive_maze_30_1       30.0    1.0   
1   2025-09-20 13:14:42    recursive_maze_30_2       30.0    2.0   
2   2025-09-20 13:14:42    recursive_maze_30_3       30.0    3.0   
3   2025-09-20 13:14:42    recursive_maze_30_4       30.0    4.0   
4   2025-09-20 13:14:42    recursive_maze_30_5       30.0    5.0   
..                  ...                    ...        ...    ...   
95  2025-09-20 13:14:43   recursive_maze_30_96       30.0   96.0   
96  2025-09-20 13:14:43   recursive_maze_30_97       30.0   97.0   
97  2025-09-20 13:14:43   recursive_maze_30_98       30.0   98.0   
98  2025-09-20 13:14:43   recursive_maze_30_99       30.0   99.0   
99  2025-09-20 13:14:43  recursive_maze_30_100       30.0  100.0   

                 algorithm  generation_time_ms  ram_peak_mb  file_size_bytes  \
0   recursive_backtracking                5.00        17.91           3843.0   
1   recursive_backtracking                9.99        17.91           3843.0   
2   recursive_backtracking                6.92        17.92           3843.0   
3   recursive_backtracking                6.21        17.96           3843.0   
4   recursive_backtracking                7.88        17.97           3843.0   
..                     ...                 ...          ...              ...   
95  recursive_backtracking                5.08        18.01           3843.0   
96  recursive_backtracking                7.11        18.01           3843.0   
97  recursive_backtracking                5.59        18.01           3843.0   
98  recursive_backtracking                7.33        18.01           3843.0   
99  recursive_backtracking                5.39        18.01           3843.0   

    backtrack_count  edges_processed  union_find_operations  
0              94.0            899.0                    0.0  
1              92.0            899.0                    0.0  
2              89.0            899.0                    0.0  
3              85.0            899.0                    0.0  
4              89.0            899.0                    0.0  
..              ...              ...                    ...  
95             88.0            899.0                    0.0  
96             87.0            899.0                    0.0  
97             92.0            899.0                    0.0  
98             93.0            899.0                    0.0  
99             91.0            899.0                    0.0  

[100 rows x 11 columns]

In [61]:
max_recursive_30 = duckdb.sql("""
SELECT max("generation_time_ms")
from df_recursive_maze_30
""").df()
max_recursive_30

max(generation_time_ms)
0                    18.86

In [63]:
mean_recursive_30 = duckdb.sql("""
SELECT mean("generation_time_ms")
from df_recursive_maze_30
""").df()
mean_recursive_30

mean(generation_time_ms)
0                    6.5259

In [67]:
count_max_recursive_30 = duckdb.sql("""
SELECT filename
from df_recursive_maze_30
where generation_time_ms > 14
""").df()
count_max_recursive_30

filename
0  recursive_maze_30_30
1  recursive_maze_30_33

In [68]:
# création data frame dfs taille 30
df= pd.read_csv("constructors_metrics.csv")
df_kruskal_30 = duckdb.sql("""
SELECT * 
FROM df 
where maze_size = 30 and algorithm= 'kruskal'
""").df()
df_kruskal_30

timestamp                   filename  maze_size   seed  \
0   2025-09-20 13:18:10    kruskal_strict_30_1.txt       30.0    1.0   
1   2025-09-20 13:18:10    kruskal_strict_30_2.txt       30.0    2.0   
2   2025-09-20 13:18:10    kruskal_strict_30_3.txt       30.0    3.0   
3   2025-09-20 13:18:10    kruskal_strict_30_4.txt       30.0    4.0   
4   2025-09-20 13:18:10    kruskal_strict_30_5.txt       30.0    5.0   
..                  ...                        ...        ...    ...   
95  2025-09-20 13:18:11   kruskal_strict_30_96.txt       30.0   96.0   
96  2025-09-20 13:18:11   kruskal_strict_30_97.txt       30.0   97.0   
97  2025-09-20 13:18:11   kruskal_strict_30_98.txt       30.0   98.0   
98  2025-09-20 13:18:11   kruskal_strict_30_99.txt       30.0   99.0   
99  2025-09-20 13:18:11  kruskal_strict_30_100.txt       30.0  100.0   

   algorithm  generation_time_ms  ram_peak_mb  file_size_bytes  \
0    kruskal                3.64        18.18           3843.0   
1    kruskal                3.76        18.19           3843.0   
2    kruskal                4.54        18.19           3843.0   
3    kruskal                7.25        18.19           3843.0   
4    kruskal               12.39        18.19           3843.0   
..       ...                 ...          ...              ...   
95   kruskal                3.81        18.19           3843.0   
96   kruskal                3.55        18.19           3843.0   
97   kruskal                3.41        18.19           3843.0   
98   kruskal                3.75        18.19           3843.0   
99   kruskal                3.92        18.19           3843.0   

    backtrack_count  edges_processed  union_find_operations  
0               0.0           1740.0                 6672.0  
1               0.0           1740.0                 6491.0  
2               0.0           1740.0                 7153.0  
3               0.0           1740.0                 6998.0  
4               0.0           1740.0                 6602.0  
..              ...              ...                    ...  
95              0.0           1740.0                 6483.0  
96              0.0           1740.0                 7120.0  
97              0.0           1740.0                 6704.0  
98              0.0           1740.0                 7098.0  
99              0.0           1740.0                 7045.0  

[100 rows x 11 columns]

In [69]:
max_kruskal_30 = duckdb.sql("""
SELECT max("generation_time_ms")
from df_kruskal_30
""").df()
max_kruskal_30

max(generation_time_ms)
0                    12.39

In [71]:
mean_kruskal_30 = duckdb.sql("""
SELECT mean("generation_time_ms")
from df_kruskal_30
""").df()
mean_kruskal_30

mean(generation_time_ms)
0                    4.1058

In [72]:
# création data frame dfs taille 30
df= pd.read_csv("constructors_metrics.csv")
df_kruskal_20 = duckdb.sql("""
SELECT * 
FROM df 
where maze_size = 20 and algorithm= 'kruskal'
""").df()
df_kruskal_20

timestamp                   filename  maze_size   seed  \
0   2025-09-20 13:18:10    kruskal_strict_20_1.txt       20.0    1.0   
1   2025-09-20 13:18:10    kruskal_strict_20_2.txt       20.0    2.0   
2   2025-09-20 13:18:10    kruskal_strict_20_3.txt       20.0    3.0   
3   2025-09-20 13:18:10    kruskal_strict_20_4.txt       20.0    4.0   
4   2025-09-20 13:18:10    kruskal_strict_20_5.txt       20.0    5.0   
..                  ...                        ...        ...    ...   
95  2025-09-20 13:18:10   kruskal_strict_20_96.txt       20.0   96.0   
96  2025-09-20 13:18:10   kruskal_strict_20_97.txt       20.0   97.0   
97  2025-09-20 13:18:10   kruskal_strict_20_98.txt       20.0   98.0   
98  2025-09-20 13:18:10   kruskal_strict_20_99.txt       20.0   99.0   
99  2025-09-20 13:18:10  kruskal_strict_20_100.txt       20.0  100.0   

   algorithm  generation_time_ms  ram_peak_mb  file_size_bytes  \
0    kruskal                2.22        17.91           1763.0   
1    kruskal                2.08        17.94           1763.0   
2    kruskal                1.90        17.94           1763.0   
3    kruskal                2.63        17.94           1763.0   
4    kruskal               15.53        17.94           1763.0   
..       ...                 ...          ...              ...   
95   kruskal                2.01        17.96           1763.0   
96   kruskal                1.74        17.96           1763.0   
97   kruskal                2.31        17.96           1763.0   
98   kruskal                2.00        17.96           1763.0   
99   kruskal                1.79        17.96           1763.0   

    backtrack_count  edges_processed  union_find_operations  
0               0.0            760.0                 2969.0  
1               0.0            760.0                 2661.0  
2               0.0            760.0                 2913.0  
3               0.0            760.0                 2908.0  
4               0.0            760.0                 2858.0  
..              ...              ...                    ...  
95              0.0            760.0                 3084.0  
96              0.0            760.0                 2836.0  
97              0.0            760.0                 2716.0  
98              0.0            760.0                 2650.0  
99              0.0            760.0                 2556.0  

[100 rows x 11 columns]

In [73]:
max_kruskal_20 = duckdb.sql("""
SELECT max("generation_time_ms")
from df_kruskal_20
""").df()
max_kruskal_20

max(generation_time_ms)
0                    15.53

In [74]:
mean_kruskal_20 = duckdb.sql("""
SELECT mean("generation_time_ms")
from df_kruskal_20
""").df()
mean_kruskal_20

mean(generation_time_ms)
0                    2.4349

In [77]:
mean_kruskal_20 = duckdb.sql("""
SELECT filename
from df_kruskal_20
where generation_time_ms > 8
""").df()
mean_kruskal_20

filename
0  kruskal_strict_20_5.txt

In [ ]:
df_clean = duckdb.sql("""
UPDATE df
SET generation_time = select mean(generation_time) from df_kruskal_20
WHERE filename = kruskal_strict_20_5.txt
""").df()

df_clean = duckdb.sql("""
UPDATE df
SET generation_time = mean(generation_time)
WHERE filename = kruskal_strict_20_5.txt
""").df()
